apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-js
  labels:
    app: next-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-js
  template:
    metadata:
      labels:
        app: next-js
    spec:
      containers:
      - name: next-js-pod
        image: 252458297036.dkr.ecr.ap-northeast-2.amazonaws.com/next-js-playground:prod-fec1d5a
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: next-js-service
  labels:
    app: next-js-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: next-js